name: Playwright Tests with Allure Reports

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'    

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install  
        
        env:
          VALID_LOGIN: ${{ secrets.VALID_LOGIN }}
          VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
      
      # Step 5: Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test --reporter=line,allure-playwright

      # Step 6: Generate Allure report
      - name: Generate Allure report
        run: npx allure generate allure-results --clean -o allure-report

      # Step 7: Deploy Allure Report to gh-pages
      - name: Deploy Allure Report to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages

         
